### PR TITLE
little rewrite, made things more readable and modern (i tried)

### PR DESCRIPTION
**Pull request by svqzd**
basically made everything classes for more *typescript*

### CODE REVIEW

**Comment by jaculate** [comment]
fwd @Kurpp

**Review by jaculate — CHANGES_REQUESTED** [review]
Please make folders have consistent names (some have uppercase and some have lowercase, e.x database should be Database)

**Comment by G6F** [comment]
trash code; a monkey could have done better$

**Comment by jaculate** [comment]
also @svqzd have you tested all routes to ensure this is working?

**Comment by Kurpp** [comment]
Most of this code seems quite redundant and I have a few reasons as to why

- Envalid seems like a useless dependency because you can accomplish most of the things that package does with `JSON.parse()`

- Although I enjoy OOP I feel like the use case here is quite extreme, and has little to no benefit

1. It requires a lot more boilerplate code, and sacrifices quite a bit of readability 
2. The classes explicit types aren't really required because most of them can be automatically inferred (and be assigned before being created)
3. Exporting and Importing the instance from index is pointless because you can access it from [req.app](http://expressjs.com/en/5x/api.html#req.app)

The pr seems to add a closer relation to java with how these classes are built and adds no real functionality or benefit (imo)
I'm interested to hear your pov on this though

**Comment by svqzd** [comment]
> Most of this code seems quite redundant and I have a few reasons as to why
> 
> * Envalid seems like a useless dependency because you can accomplish most of the things that package does with `JSON.parse()`
> * Although I enjoy OOP I feel like the use case here is quite extreme, and has little to no benefit
> 
> 1. It requires a lot more boilerplate code, and sacrifices quite a bit of readability
> 2. The classes explicit types aren't really required because most of them can be automatically inferred (and be assigned before being created)
> 3. Exporting and Importing the instance from index is pointless because you can access it from [req.app](http://expressjs.com/en/5x/api.html#req.app)
> 
> The pr seems to add a closer relation to java with how these classes are built and adds no real functionality or benefit (imo) I'm interested to hear your pov on this though

fair enough, i will try to fix most of the things youve said here and resubmit if thats a possibility

**Pull request closed without merging**
